version: '3.7'

services:
  db:
    image: mysql:8.0
    deploy:
       replicas: 3
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=exampledb
      - MYSQL_USER=exampleuser
      - MYSQL_PASSWORD=examplepass
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'

  wordpress:
    depends_on:
      - db
    image: wordpress:6.1.1-php7.4-fpm
    deploy:
       replicas: 3
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=exampleuser
      - WORDPRESS_DB_PASSWORD=examplepass
      - WORDPRESS_DB_NAME=exampledb
    volumes:
      - wordpress:/var/www/html
   
  webserver:
    depends_on:
      - wordpress
    image: nginx:latest
    deploy:
       replicas: 3
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
volumes:
  wordpress:
  dbdata:

